[debug]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5
read_timeout = 5
write_timeout = 5
limits = {form = 32768, file = "32MiB"}

[release]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5
read_timeout = 5
write_timeout = 5
limits = { form = 32768, file = "32MiB"}